### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by y-kisel** [DzodzikovAK/operations-repository#2]
I think we should implement multimodule structure with following modules:
* core - everything to start operation processing
* fs-repository - module with operations in file system
* db-repository - module with operations in database
* web - module with REST API

**Comment by anton-dzodzikov** [comment]
If we treat this project as a full-stack operation processing solution - I agree, it makes sense.

I started it as a separate microservice whose role is to handle FS-operations, so there was no need to modularize project (due to single role).

In addition to modularization we need to rename project to something more abstract than it's current purpose.

**Comment by anton-dzodzikov** [comment]
I think we need module structure like this:

```
ROOT
---executor
---operation-storage
------filesystem-repository
------database-repository
---client
```

The idea is to deploy and run executor, client and storage separately of each other.

While client application will be offering HTTP API, there is still a question: how these applications will communicate with each other? HTTP or something else?

**Comment by y-kisel** [comment]
Each module is a brick. You can build your own app using these brick. For instance, you want an application to handle REST request and execute operation. So you use 3 modules: REST API module, core, and FS-based operations.
Another case. We want JMS based app to execute operation. Right now there is no JMS module. So, I can se core + FS-based operation executor. On top of that I implement my own JMS bridge.

**Comment by anton-dzodzikov** [comment]
Do you mean that the app should be built as single monolithic application?

**Comment by y-kisel** [comment]
Hy not if you want so?
But on the other hand, what is difference between monolitic architecture and microservice? In general, there is no difference - both are applications.
From my point of view, we should provide tools. Our user should decide what to build using these tools - monolitic, microservice, reactive, or another type of application.

**Comment by anton-dzodzikov** [comment]
Faced this in https://github.com/anton-dzodzikov/lightprocessing/pull/5
